repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.8
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
    - id: ty-check
      name: ty-check
      language: python
      entry: ty check
      pass_filenames: false
      args: [--python=.venv/]
      additional_dependencies: [ty]